"""add case bookmarks

Revision ID: 38a050b8c1fa
Revises: 8aa3239e9f32
Create Date: 2026-09-18 15:51:39.199457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a050b8c1fa'
down_revision: Union[str, Sequence[str], None] = '8aa3239e9f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('bookmark_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_bookmarks_case_id'), 'case_bookmarks', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_bookmarks_created_by'), 'case_bookmarks', ['created_by'], unique=False)
    op.create_index(op.f('ix_case_bookmarks_id'), 'case_bookmarks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_bookmarks_id'), table_name='case_bookmarks')
    op.drop_index(op.f('ix_case_bookmarks_created_by'), table_name='case_bookmarks')
    op.drop_index(op.f('ix_case_bookmarks_case_id'), table_name='case_bookmarks')
    op.drop_table('case_bookmarks')
    # ### end Alembic commands ###
