"""add case reports

Revision ID: 92fd6171cf29
Revises: 38a050b8c1fa
Create Date: 2026-09-18 16:11:00.071395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fd6171cf29'
down_revision: Union[str, Sequence[str], None] = '38a050b8c1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_reports_case_id'), 'case_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_reports_created_by'), 'case_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_case_reports_id'), 'case_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_reports_id'), table_name='case_reports')
    op.drop_index(op.f('ix_case_reports_created_by'), table_name='case_reports')
    op.drop_index(op.f('ix_case_reports_case_id'), table_name='case_reports')
    op.drop_table('case_reports')
    # ### end Alembic commands ###
